/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hiandlowTest222.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Box2(props) {
  const { nodes, materials } = useGLTF("/models/hiandlowTest222.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.low.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/hiandlowTest222.glb");
