/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hiandlowTest333.glb 
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Box3(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/hiandlowTest333.glb",
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="low"
          geometry={nodes.low.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/hiandlowTest333.glb");
