/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hiandlowTest333.glb 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useTexture } from "@react-three/drei";
import { useFrame } from "@react-three/fiber"; // useFrame 임포트 추가
import * as THREE from "three";

export function Box3({ currentAction, isLooping = true, ...props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/hiandlowTest333.glb",
  );
  const { actions } = useAnimations(animations, group);

  const newTexture = useTexture("/models/Wood-6986.jpg");

  // 1. React 상태가 바뀔 때 애니메이션 최초 실행 및 설정
  useEffect(() => {
    const action = actions[currentAction];

    if (action) {
      action.reset().stop(); // 이전 흔적을 완전히 지우고 0프레임 정지상태로 리셋

      if (isLooping) {
        action.setLoop(THREE.LoopRepeat, Infinity);
        action.clampWhenFinished = false;
      } else {
        // 1회 재생 설정 (마지막 프레임에 고정하되, useFrame에서 가로챌 예정)
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = true;
      }

      action.fadeIn(0.2).play();
    }

    return () => {
      if (action) action.fadeOut(0.2);
    };
  }, [currentAction, isLooping, actions]);

  // 2. [핵심] 매 프레임마다 Three.js 내부 타임라인을 직접 감시 (초당 60회 이상)
  useFrame(() => {
    const action = actions[currentAction];
    // 반복 재생 모드이거나 액션이 없으면 감시하지 않음
    if (!action || isLooping) return;

    // 애니메이션의 현재 진행 시간이 총 길이(duration)에 도달했는지 실시간 체크
    const duration = action.getClip().duration;

    if (action.time >= duration - 0.01) {
      // 1회 재생이 끝나면 즉시 실행 중지하고 0프레임으로 강제 타임워프
      action.stop();
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="low" geometry={nodes.low.geometry} castShadow receiveShadow>
          <meshStandardMaterial
            {...materials["Material.001"]}
            // map={newTexture}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/hiandlowTest333.glb");
