/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hiandlowTest333.glb 
*/

import React, { useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import * as THREE from "three"; // 루프 설정을 위해 THREE 임포트 추가

export function Box3({ currentAction, isLooping = true, ...props }) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/hiandlowTest333.glb",
  );
  const { actions, mixer } = useAnimations(animations, group);

  useEffect(() => {
    if (!mixer) return;

    const handleFinished = (e) => {
      // 1회 재생이 끝난 애니메이션을 강제로 stop시켜서 0프레임 대기 상태로 만듭니다.
      if (e.action) {
        e.action.stop();
      }
    };

    mixer.addEventListener("finished", handleFinished);

    return () => {
      mixer.removeEventListener("finished", handleFinished);
    };
  }, [mixer]);

  // 애니메이션 제어를 위한 useEffect 추가
  useEffect(() => {
    // 1. 현재 요청된 애니메이션이 actions에 존재하는지 확인
    const action = actions[currentAction];

    if (action) {
      action.stop(); // 현재 애니메이션이 재생 중이라면 멈춤

      // 3. 루프(반복) 여부 설정
      if (isLooping) {
        action.setLoop(THREE.LoopRepeat, Infinity);
        action.clampWhenFinished = false;
      } else {
        // 한 번만 재생하고 마지막 프레임에서 멈춤
        action.setLoop(THREE.LoopOnce, 1);
        action.clampWhenFinished = false;
      }

      action.fadeIn(0.2).play();
    }

    // 4. Clean-up: 다른 애니메이션으로 바뀔 때 이전 애니메이션을 부드럽게 끄기
    return () => {
      if (action) action.fadeOut(0.2);
    };
  }, [currentAction, isLooping, actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="low"
          geometry={nodes.low.geometry}
          material={materials["Material.001"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/hiandlowTest333.glb");
