/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 hiandlowTest111.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Boxtest(props) {
  const { nodes, materials } = useGLTF("/models/hiandlowTest111.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.hi.geometry} material={nodes.hi.material} />
      <mesh
        geometry={nodes.low.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/models/hiandlowTest111.glb");
