/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as GsapRouteImport } from './routes/gsap'
import { Route as DevRouteImport } from './routes/dev'
import { Route as IndexRouteImport } from './routes/index'

const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const GsapRoute = GsapRouteImport.update({
  id: '/gsap',
  path: '/gsap',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/gsap': typeof GsapRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/gsap': typeof GsapRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev': typeof DevRoute
  '/gsap': typeof GsapRoute
  '/production': typeof ProductionRoute
  '/quality': typeof QualityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dev' | '/gsap' | '/production' | '/quality'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dev' | '/gsap' | '/production' | '/quality'
  id: '__root__' | '/' | '/dev' | '/gsap' | '/production' | '/quality'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevRoute: typeof DevRoute
  GsapRoute: typeof GsapRoute
  ProductionRoute: typeof ProductionRoute
  QualityRoute: typeof QualityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gsap': {
      id: '/gsap'
      path: '/gsap'
      fullPath: '/gsap'
      preLoaderRoute: typeof GsapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevRoute: DevRoute,
  GsapRoute: GsapRoute,
  ProductionRoute: ProductionRoute,
  QualityRoute: QualityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
